# Generated by Django 4.0.3 on 2022-07-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main_gif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=122)),
                ('image', models.FileField(upload_to='main_gif/%Y/%m/%d/')),
            ],
        ),
    ]
