# Generated by Django 4.0.3 on 2022-07-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('best_games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='best_games',
            name='image',
            field=models.FileField(upload_to='best_games/%Y/%m/%d/'),
        ),
    ]
