# Generated by Django 4.0.6 on 2022-07-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port228', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='port228',
            name='image',
            field=models.ImageField(default=1, upload_to='media/image'),
            preserve_default=False,
        ),
    ]
