# Generated by Django 4.0.6 on 2022-07-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port228', '0002_port228_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port228',
            name='image',
            field=models.ImageField(upload_to='port228/%Y/%m/%d/'),
        ),
    ]
