# Generated by Django 4.0.3 on 2022-07-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port228', '0003_alter_port228_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port228',
            name='image',
            field=models.FileField(upload_to='port228/%Y/%m/%d/'),
        ),
    ]
